<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Deep_Learning_with_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentals of Tensorflow**

We are going to cover :


1.   Introductions to Tensors
2.   Getting informations from Tensors
3.   Manipulating Tensors
4.   Tensors & Numpy
5.   Using @tf.functions
6.   Using GPUs with Tensorflow (or TPUs)



In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__ 

'2.5.0'

## **Introductions to Tensors**

In [ ]:
# create tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[20,12],
                      [15,23]], dtype=tf.float16) # You can specify the datatype of the tensor
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[20., 12.],
       [15., 23.]], dtype=float16)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
matrix1 = tf.constant([[12,34],
                       [33,38],
                       [67,55]])
matrix1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 34],
       [33, 38],
       [67, 55]], dtype=int32)>

In [ ]:
matrix1.ndim # This dimension is according to the number of contents inside the shape

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[12,33,11],
                       [23,45,56],
                       [12,33,43]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[12, 33, 11],
        [23, 45, 56],
        [12, 33, 43]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tensor1 = tf.constant([[[[12,23],
                         [15,32],
                         [78,23]]]])
tensor1

<tf.Tensor: shape=(1, 1, 3, 2), dtype=int32, numpy=
array([[[[12, 23],
         [15, 32],
         [78, 23]]]], dtype=int32)>

In [ ]:
tensor1.ndim

4

## Creating Tensor with tf.Variable

In [ ]:
# Creating Tensor with "tf.Variable"
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change the changeable tensor
changeable_tensor[0] = 80

TypeError: ignored

In [ ]:
# Let's try to change the changeable tensor with ".assign"
changeable_tensor[0].assign(80)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([80,  7], dtype=int32)>

In [ ]:
# Let's try to change the unchangeable tensor with ".assign"
unchangeable_tensor[0].assign(90)
unchangeable_tensor

AttributeError: ignored

##  Random Value tensors

In [ ]:
# Create two random value(but the same) tensors 

random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# are they equal ?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the elements of a tensor

In [ ]:
### Shuffle the elements of the tensors randomly
unshuffled_tensor = tf.constant([[10,7],
                                 [20,9],
                                 [33,41]])
unshuffled_tensor.ndim

2

In [ ]:
# Shuffle the unshuffled tensor
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(unshuffled_tensor, seed=42) # Local operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [20,  9],
       [33, 41]], dtype=int32)>

## Numpy way of creating tensors
#### Nupmy arrays can be turned to tensors as tensors are capable of running in GPUs     

In [ ]:
import numpy as np

x = np.ones((3,2,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
tf.ones((3,2,4))

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
x_tensor = tf.constant(x)
x_tensor

<tf.Tensor: shape=(3, 2, 4), dtype=float64, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])>

In [ ]:
x_tensor.ndim

3

In [ ]:
# we can change the dimension of the tensor as long as the number of elements remain same in the tensor

x_tensor = tf.constant(x, shape=(3,3,3)) # this cannot be done as the original number of elements in the tensor is changed

TypeError: ignored

In [ ]:
x_tensor = tf.constant(x, shape=(2,2,2,3))
x_tensor.ndim # dimension changed

4

In [ ]:
# Create scalar, vector and matrices using np.array
x_exp = np.array((2,3,4,5), ndmin=2)

In [ ]:
x_exp

array([[2, 3, 4, 5]])

## Getting information from tensors
1.   Shape
2.   Rank
3.   Axis or dimension
4.   Size



In [ ]:
# Create a tensor of rank 4 (4-dimensions)
rank_4_tensor = tf.zeros((2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## Indexing Tensors
Tensors can be indexed just like Python tensors

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

## Matrix multiplication

1. Using tf.linalg.matmul or tf.matmul
2. We can multiply using @ operator

In [ ]:
# Matric multiplication can be done using Linaer Algebra package as well as inbuilt "matmul"
tensor_mul = tf.constant([[10,7],
                          [3,4]])

In [ ]:
# Both Linear Algebra matmul and inbuilt matmul produce same result
tf.matmul(tensor_mul, tensor_mul) , tf.linalg.matmul(tensor_mul, tensor_mul)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [8]:
tensor_mul1 = tf.constant([[3,4,5],
                           [18,12,3]])
tensor_mul2 = tf.constant([[6,4,9],
                          [3,5,6]])

In [9]:
# Let's try to multiply two [2X3] matrices
tf.matmul(tensor_mul1, tensor_matmul2)

NameError: ignored

In [10]:
# Now let's change the shape of matmul2
tf.reshape(tensor_mul2, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 4],
       [9, 3],
       [5, 6]], dtype=int32)>

In [12]:
# Now let's multiply tensor_mul1 and tensor_mul2
tf.matmul(tensor_mul1, tf.reshape(tensor_mul2, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79,  54],
       [231, 126]], dtype=int32)>

In [13]:
# We can use transpose as well to multiply
tf.matmul(tensor_mul1, tf.transpose(tensor_mul2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79,  59],
       [183, 132]], dtype=int32)>