<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Deep_Learning_with_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentals of Tensorflow**

We are going to cover :


1.   Introductions to Tensors
2.   Getting informations from Tensors
3.   Manipulating Tensors
4.   Tensors & Numpy
5.   Using @tf.functions
6.   Using GPUs with Tensorflow (or TPUs)



In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__ 

'2.5.0'

## **Introductions to Tensors**

In [ ]:
# create tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[20,12],
                      [15,23]], dtype=tf.float16) # You can specify the datatype of the tensor
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[20., 12.],
       [15., 23.]], dtype=float16)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
matrix1 = tf.constant([[12,34],
                       [33,38],
                       [67,55]])
matrix1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 34],
       [33, 38],
       [67, 55]], dtype=int32)>

In [ ]:
matrix1.ndim # This dimension is according to the number of contents inside the shape

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[12,33,11],
                       [23,45,56],
                       [12,33,43]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[12, 33, 11],
        [23, 45, 56],
        [12, 33, 43]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tensor1 = tf.constant([[[[12,23],
                         [15,32],
                         [78,23]]]])
tensor1

<tf.Tensor: shape=(1, 1, 3, 2), dtype=int32, numpy=
array([[[[12, 23],
         [15, 32],
         [78, 23]]]], dtype=int32)>

In [ ]:
tensor1.ndim

4

## Creating Tensor with tf.Variable

In [ ]:
# Creating Tensor with "tf.Variable"
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change the changeable tensor
changeable_tensor[0] = 80

TypeError: ignored

In [ ]:
# Let's try to change the changeable tensor with ".assign"
changeable_tensor[0].assign(80)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([80,  7], dtype=int32)>

In [ ]:
# Let's try to change the unchangeable tensor with ".assign"
unchangeable_tensor[0].assign(90)
unchangeable_tensor

AttributeError: ignored

##  Random Value tensors

In [ ]:
# Create two random value(but the same) tensors 

random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# are they equal ?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the elements of a tensor

In [ ]:
### Shuffle the elements of the tensors randomly
unshuffled_tensor = tf.constant([[10,7],
                                 [20,9],
                                 [33,41]])
unshuffled_tensor.ndim

2

In [ ]:
# Shuffle the unshuffled tensor
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(unshuffled_tensor, seed=42) # Local operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [20,  9],
       [33, 41]], dtype=int32)>

## Numpy way of creating tensors
#### Nupmy arrays can be turned to tensors as tensors are capable of running in GPUs     

In [ ]:
import numpy as np

x = np.ones((3,2,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
tf.ones((3,2,4))

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
x_tensor = tf.constant(x)
x_tensor

<tf.Tensor: shape=(3, 2, 4), dtype=float64, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])>

In [ ]:
x_tensor.ndim

3

In [ ]:
# we can change the dimension of the tensor as long as the number of elements remain same in the tensor

x_tensor = tf.constant(x, shape=(3,3,3)) # this cannot be done as the original number of elements in the tensor is changed

TypeError: ignored

In [ ]:
x_tensor = tf.constant(x, shape=(2,2,2,3))
x_tensor.ndim # dimension changed

4

In [ ]:
# Create scalar, vector and matrices using np.array
x_exp = np.array((2,3,4,5), ndmin=2)

In [ ]:
x_exp

array([[2, 3, 4, 5]])

## Getting information from tensors
1.   Shape
2.   Rank
3.   Axis or dimension
4.   Size



In [ ]:
# Create a tensor of rank 4 (4-dimensions)
rank_4_tensor = tf.zeros((2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## Indexing Tensors
Tensors can be indexed just like Python tensors

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

## Matrix multiplication

1. Using tf.linalg.matmul or tf.matmul
2. We can multiply using @ operator
3. Using tf.tensordot

In [ ]:
# Matric multiplication can be done using Linaer Algebra package as well as inbuilt "matmul"
tensor_mul = tf.constant([[10,7],
                          [3,4]])

In [ ]:
# Both Linear Algebra matmul and inbuilt matmul produce same result
tf.matmul(tensor_mul, tensor_mul) , tf.linalg.matmul(tensor_mul, tensor_mul)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [ ]:
tensor_mul1 = tf.constant([[3,4,5],
                           [18,12,3]])
tensor_mul2 = tf.constant([[6,4,9],
                          [3,5,6]])

In [ ]:
# Let's try to multiply two [2X3] matrices
tf.matmul(tensor_mul1, tensor_matmul2)

NameError: ignored

In [ ]:
# Now let's change the shape of matmul2
tf.reshape(tensor_mul2, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 4],
       [9, 3],
       [5, 6]], dtype=int32)>

In [ ]:
# Now let's multiply tensor_mul1 and tensor_mul2
tf.matmul(tensor_mul1, tf.reshape(tensor_mul2, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79,  54],
       [231, 126]], dtype=int32)>

In [ ]:
# We can use transpose as well to multiply
tf.matmul(tensor_mul1, tf.transpose(tensor_mul2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79,  59],
       [183, 132]], dtype=int32)>

In [ ]:
# Multiplication using tensordot
tf.tensordot(tensor_mul1, tf.transpose(tensor_mul2), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79,  59],
       [183, 132]], dtype=int32)>

## Changing the datatype of a tensor
Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory. By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy. This guide describes how to use the Keras mixed precision API to speed up your models. Using this API can improve performance by more than 3 times on modern GPUs and 60% on TPUs.

In [ ]:
# Create a new tensor with default datatype(float32)
B = tf.constant([[1.7, 7.4],
                 [2.0, 3.0]])
B.dtype

tf.float32

In [ ]:
C = tf.constant([[7.,10.],
                [3.0,2.0]])
C.dtype

tf.float32

In [ ]:
# Change the float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [ ]:
tf.matmul(B,tf.transpose(C))

InvalidArgumentError: ignored

## Aggregating Tensor
1. Get the minimum
2. Get the maximum
3. Get the mean of a tensor
4. Get the sum of a tensor

In [ ]:
# Create a random tensor
agg_tensor = tf.constant(np.random.randint(0,100, size=50))
agg_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([72, 55, 98, 82, 31, 56, 13, 34, 90, 82, 32, 23,  1, 59, 61, 69, 81,
       43,  5, 38, 62,  5, 81,  5, 92, 29, 46, 51, 12, 43, 89, 22, 74, 53,
       40, 43, 22, 15, 77, 14, 27, 47, 86, 65,  4, 25, 77, 45, 51, 36])>

In [ ]:
tf.size(agg_tensor), agg_tensor.shape, agg_tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximun
tf.reduce_max(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

## Find the variance and standard deviation

Variance: 

Population Variance for population of size N = 
Σ
(
X
i
−
¯
X
)**2/
2
N

Sample Variance for sample of size N =  
Σ
(
X
i
−
¯
X
)**2/
2
N
−
1


In [ ]:
# To find the Variance and Standard deviation we need to access Tensorflow probability
import tensorflow_probability as tfp
variance = tfp.stats.variance(agg_tensor)

In [ ]:
# Find the standard deviation
tf.math.sqrt(tf.cast(variance, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.202942>

In [ ]:
tf.math.reduce_std(agg_tensor)

TypeError: ignored

In [ ]:
# We can also find the standard deviation using reduce_std
tf.math.reduce_std(tf.cast(agg_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.202065>

## Finding the positional minimum and maximun of the tensor

In [2]:
# Create an tensor
C = tf.random.set_seed(42)
C = tf.random.uniform(shape=[50])
C

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [3]:
# Find the positional maximum
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [4]:
C[tf.argmax(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [5]:
# Find the positional minimum
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

## Squeezing a tensor
removing all one dimensional tensors

In [13]:
tf.random.set_seed(42)
D = tf.constant(tf.random.uniform(shape=[60]), shape=(1,2,1,3,1,10)) # Shape defined
D

<tf.Tensor: shape=(1, 2, 1, 3, 1, 10), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686]],

          [[0.3103881 , 0.7223358 , 0.13318717, 0.5480639 ,
            0.5746088 , 0.8996835 , 0.00946367, 0.5212307 ,
            0.6345445 , 0.1993283 ]],

          [[0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173]]]],



        [[[[0.9485276 , 0.23752594, 0.81179297, 0.5263394 ,
            0.494308  , 0.21612847, 0.8457197 , 0.8718841 ,
            0.3083862 , 0.6868038 ]],

          [[0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]],

          [[0.6073899 , 0.46523476, 0.97803545, 0.7223145 ,
            0.32347047, 0.82577336, 0.4976915 , 0.19483674,
            0.758874

In [18]:
# Squeeze the tensor(remove all the one dimensional tensor)
D = tf.squeeze(D)
D.shape

TensorShape([2, 3, 10])

In [15]:
tf.random.set_seed(42)
E = tf.constant(tf.random.uniform(shape=[60]), shape=(1,2,1,3,1,10))
E

<tf.Tensor: shape=(1, 2, 1, 3, 1, 10), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686]],

          [[0.3103881 , 0.7223358 , 0.13318717, 0.5480639 ,
            0.5746088 , 0.8996835 , 0.00946367, 0.5212307 ,
            0.6345445 , 0.1993283 ]],

          [[0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173]]]],



        [[[[0.9485276 , 0.23752594, 0.81179297, 0.5263394 ,
            0.494308  , 0.21612847, 0.8457197 , 0.8718841 ,
            0.3083862 , 0.6868038 ]],

          [[0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]],

          [[0.6073899 , 0.46523476, 0.97803545, 0.7223145 ,
            0.32347047, 0.82577336, 0.4976915 , 0.19483674,
            0.758874

In [19]:
# Remove the one dimensional from some particular positions
E = tf.squeeze(E, [2,4])
E.shape

TensorShape([1, 2, 3, 10])

## One Hot Encoding
One hot encoding is done to convert categorical values to numerical tensor values

The locations represented by indices in indices take value on_value, while all other locations take value off_value.

on_value and off_value must have matching data types. If dtype is also provided, they must be the same data type as specified by dtype.

If on_value is not provided, it will default to the value 1 with type dtype

If off_value is not provided, it will default to the value 0 with type dtype

If the input indices is rank N, the output will have rank N+1. The new axis is created at dimension axis (default: the new axis is appended at the end).

If indices is a scalar the output shape will be a vector of length depth

If indices is a vector of length features, the output shape will be:

In [20]:
# Create some list
some_list = [0,1,2,3]

# One hot encode our list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [22]:
# Specify custom value for one hot encoding
tf.one_hot(some_list, depth=4, on_value="success", off_value="Failure", axis=-1)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'success', b'Failure', b'Failure', b'Failure'],
       [b'Failure', b'success', b'Failure', b'Failure'],
       [b'Failure', b'Failure', b'success', b'Failure'],
       [b'Failure', b'Failure', b'Failure', b'success']], dtype=object)>