<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Deep_Learning_with_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentals of Tensorflow**

We are going to cover :


1.   Introductions to Tensors
2.   Getting informations from Tensors
3.   Manipulating Tensors
4.   Tensors & Numpy
5.   Using @tf.functions
6.   Using GPUs with Tensorflow (or TPUs)



In [1]:
import tensorflow as tf

In [ ]:
tf.__version__ 

'2.5.0'

### **Introductions to Tensors**

In [ ]:
# create tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [3]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [4]:
vector.ndim

1

In [5]:
# Create a matrix
matrix = tf.constant([[20,12],
                      [15,23]], dtype=tf.float16) # You can specify the datatype of the tensor
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[20., 12.],
       [15., 23.]], dtype=float16)>

In [6]:
matrix.ndim

2

In [8]:
# Create another matrix
matrix1 = tf.constant([[12,34],
                       [33,38],
                       [67,55]])
matrix1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 34],
       [33, 38],
       [67, 55]], dtype=int32)>

In [10]:
matrix1.ndim # This dimension is according to the number of contents inside the shape

2