<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Basics/basic_tensorflow_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Tensorflow

The scalars, vectors and matrix all are tensors by concept.All can be created using basic tf.constant(). Only difference is scalar has no dimension, vector has 1 and matrix vector has 2 or more.

In [6]:
import tensorflow as tf

scalar = tf.constant(7) # A simple value is pushed
scalar.ndim , scalar.shape

(0, TensorShape([]))

In [3]:
vector = tf.constant([2,4]) # A list is pushed in the tf.constant()
vector.ndim

1

In [5]:
matrix = tf.constant([[7,10],
                     [10,7]]) # A two-dimensional matrix is pushed into the tf.constant()

matrix.ndim

2

By default the data type is int32. we can change this to int64 which will take more space or we can change the data type to float16

In [7]:
float_matrix = tf.constant([[8.6, 3.4],
                           [5.8, 8.2]], dtype=tf.float16)
float_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[8.6, 3.4],
       [5.8, 8.2]], dtype=float16)>

In [8]:
# What is the dimension of float_matrix ?
float_matrix.ndim

2

We can notice that the dimension of the tensor is equal to the number elements in the shape. Basically the number of rows in the tensor is the dimension

In [9]:
# Create a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[14,15,16],
                       [17,18,19]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[14, 15, 16],
        [17, 18, 19]]], dtype=int32)>

In [10]:
# dimension of the tensor
tensor.ndim

3