<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Basics/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentals of Tensorflow**

* Introduction to Tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function ( a way to speed up your regular Python Functions)
* Using GPUs with Tensorflow (or TPUs)

## Create Tensors with tf.constant()

In [2]:
import tensorflow as tf

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [4]:
# create matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])

In [5]:
matrix.ndim

2

The general observation is that number of brackets actually signifies the dimension of the tensor

In [9]:
another_matrix = tf.constant([[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]], dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>

In the above code changing the dtype of the tensor saves space as by default tensorflow tensors are int32

Show that the dimension of the tensors depends upon the brackets of the tensorflow

In [10]:
tensor = tf.constant([[[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]]])

tensor

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [11]:
tensor_1 = tf.constant([[[[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]]]])

tensor_1

<tf.Tensor: shape=(1, 1, 2, 2, 3), dtype=int32, numpy=
array([[[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]]]], dtype=int32)>

In [12]:
tensor.ndim, tensor_1.ndim

(4, 5)

## Create Tensors with tf.variable()

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

We cannot directly assign values of an element of a tensor, we need to use .assign() function

In [15]:
changeable_tensor[0].assign(34)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([34,  7], dtype=int32)>

In [16]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([34,  7], dtype=int32)>

## Create Random Tensors

In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed
random_1 = random_1.normal(shape = (3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)