<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Basics/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentals of Tensorflow**

* Introduction to Tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function ( a way to speed up your regular Python Functions)
* Using GPUs with Tensorflow (or TPUs)

In [2]:
import tensorflow as tf

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [4]:
# create matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])

In [5]:
matrix.ndim

2

The general observation is that number of brackets actually signifies the dimension of the tensor

In [9]:
another_matrix = tf.constant([[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]], dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>

In the above code changing the dtype of the tensor saves space as by default tensorflow tensors are int32

Show that the dimension of the tensors depends upon the brackets of the tensorflow

In [10]:
tensor = tf.constant([[[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]]])

tensor

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [11]:
tensor_1 = tf.constant([[[[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]]]])

tensor_1

<tf.Tensor: shape=(1, 1, 2, 2, 3), dtype=int32, numpy=
array([[[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]]]], dtype=int32)>

In [12]:
tensor.ndim, tensor_1.ndim

(4, 5)