<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Tensorflow/blob/main/Basics/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentals of Tensorflow**

* Introduction to Tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function ( a way to speed up your regular Python Functions)
* Using GPUs with Tensorflow (or TPUs)

## What Hardware resources you are using

In [81]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [82]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Create Tensors with tf.constant()

In [1]:
import tensorflow as tf

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [2]:
# create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [3]:
# create matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])

In [4]:
matrix.ndim

2

The general observation is that number of brackets actually signifies the dimension of the tensor

In [5]:
another_matrix = tf.constant([[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]], dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>

In the above code changing the dtype of the tensor saves space as by default tensorflow tensors are int32

Show that the dimension of the tensors depends upon the brackets of the tensorflow

In [6]:
tensor = tf.constant([[[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]]])

tensor

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [7]:
tensor_1 = tf.constant([[[[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]]]])

tensor_1

<tf.Tensor: shape=(1, 1, 2, 2, 3), dtype=int32, numpy=
array([[[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]]]], dtype=int32)>

In [8]:
tensor.ndim, tensor_1.ndim

(4, 5)

## Create Tensors with tf.variable()

In [9]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

We cannot directly assign values of an element of a tensor, we need to use .assign() function

In [10]:
changeable_tensor[0].assign(34)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([34,  7], dtype=int32)>

In [11]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([34,  7], dtype=int32)>

## Create Random Tensors

In [12]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed
random_1 = random_1.normal(shape = (3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle The Random Tensor

In [13]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [14]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

## Other Ways of Creating Tensors

In [15]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.zeros(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## Create Tensor from Numpy

In [17]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [18]:
A = tf.constant(numpy_A, shape = (2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [19]:
numpy_A.shape, A.shape

((24,), TensorShape([2, 3, 4]))

## Getting Information From Tensor

* Shape
* Rank
* Axis or dimension
* Size

In [20]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [22]:
# Get various attributes of the tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


## Indexing Tensors

In [23]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [24]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
# Get first element from dimension from each index except from the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_2_tensor = tf.random.uniform(minval=0,maxval=50, shape=(2,2))
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[30.841572, 13.50416 ],
       [47.13757 , 25.728655]], dtype=float32)>

In [27]:
# Get the last element of each row of rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([13.50416 , 25.728655], dtype=float32)>

## Add new dimension to the tensors

In [28]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[30.841572],
        [13.50416 ]],

       [[47.13757 ],
        [25.728655]]], dtype=float32)>

In [29]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[30.841572],
        [13.50416 ]],

       [[47.13757 ],
        [25.728655]]], dtype=float32)>

## Manipulating Tensors (Tensor Operations)

In [30]:
# Basic maths operatiosn
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [31]:
tensor * 25

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[250, 175],
       [ 75, 100]], dtype=int32)>

In [32]:
tensor - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [33]:
# Using built-in functions
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix Multiplication

In [34]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [35]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
# Multiplication of tensors using tensors of different shape
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In matrix multiplication as by basic mathematics row of matrix A should be equal to columns of matrix B

In the perspective of tensors, inner dimensions should match

In [37]:
# To achive the matrix multiplication we can reshape the matrix
tf.reshape(Y, shape = (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [38]:
# try to matrix multiply X with reshaped Y
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [39]:
X @ tf.reshape(Y, shape = (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [40]:
tf.tensordot(X, tf.reshape(Y, shape = (2, 3)), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [41]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## Changing the datatype of tensors

In [42]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [43]:
C = tf.constant([7, 10])
C.dtype

tf.int32

Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory. By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy. This guide describes how to use the Keras mixed precision API to speed up your models. Using this API can improve performance by more than 3 times on modern GPUs, 60% on TPUs and more than 2 times on latest Intel CPUs.

In [44]:
# changing the datatype from float32 and int32 to float16 and int16

In [45]:
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

## Aggregating Tensors
Aggregating tensors = condensing them from multiple values to smaller amount of values

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [46]:
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([58, 98, 34, 15, 27,  6,  6, 40, 42, 66, 21, 59, 43, 97, 11, 33, 75,
       49, 83, 85, 94,  2, 20, 80, 43, 42, 94, 94, 38, 96, 90,  0, 68, 52,
       18,  4,  2, 76, 87, 19, 85, 92, 49, 60, 63, 26, 74, 37,  6, 76])>

In [47]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [48]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [49]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [50]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2535>

In [52]:
tf.reduce_std(E)

AttributeError: module 'tensorflow' has no attribute 'reduce_std'

Find Variance and Standard deviation of a tensor. tensorflow package doesn't have any variance or standard deviation methods for that we need to import tensorflow_probality

In [53]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=979>

In [54]:
tfp.stats.stddev(E)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

Reduces input_tensor along the dimensions given in axis. Unless keepdims is true, the rank of the tensor is reduced by 1 for each of the entries in axis, which must be unique. If keepdims is true, the reduced dimensions are retained with length 1.

If axis is None, all dimensions are reduced, and a tensor with a single element is returned.

If you write this:

tf.math.reduce_std(E)

you will get error :

TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.

In [55]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.282743>

## Find Positional maximum and minimum

In [56]:
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.49665952, 0.6632519 , 0.25878727, 0.92585826, 0.4590832 ,
       0.9317962 , 0.992334  , 0.8185923 , 0.7450923 , 0.6653129 ,
       0.6667987 , 0.86642015, 0.67818475, 0.2982602 , 0.60849535,
       0.11691403, 0.73090935, 0.35010266, 0.3981514 , 0.6826005 ,
       0.86256504, 0.65411186, 0.7565435 , 0.5786408 , 0.7352122 ,
       0.55613303, 0.2257533 , 0.06816435, 0.93476367, 0.366688  ,
       0.94942355, 0.00771952, 0.3026049 , 0.69325054, 0.25031734,
       0.22520232, 0.26675212, 0.498878  , 0.36013448, 0.00929999,
       0.9760262 , 0.44182897, 0.7209277 , 0.20701349, 0.80271316,
       0.3406192 , 0.48962176, 0.6380408 , 0.19401717, 0.22859097],
      dtype=float32)>

In [64]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [57]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.992334>

In [62]:
# Position of maximum value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.992334>

In [63]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

## One Hot encoding in Tensorflow

In [71]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

The locations represented by indices in indices take value on_value, while all other locations take value off_value.

on_value and off_value must have matching data types. If dtype is also provided, they must be the same data type as specified by dtype.

If on_value is not provided, it will default to the value 1 with type dtype

If off_value is not provided, it will default to the value 0 with type dtype

In the above example some_list mentions the position of the 1s in each row.

## Squaring,Log, Square root

In [72]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [73]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [74]:
# Find square root
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

A common pattern solution is observed that if the error comes from any tensorflow casting, it usually due to datatype. There is a common solution for that to change the datatype by `tf.cast()` function

In [77]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Tensors and Numpy

Difference between Tensor and Numpy is that Tensors can use GPU or TPU of the system

In [78]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [79]:
# Convert back tensor to Numpy array
np.array(J)

array([ 3.,  7., 10.])

In [80]:
# Another way to convert tensor to numpy
J.numpy()

array([ 3.,  7., 10.])